name: Publish binaries

on:
  push:
    # branches: [master,develop]
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Publish node cli binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: List
      run: ls
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: install pkg
      run: npm install -g pkg@latest
    - name: package
      run: pkg --targets node16-linux-x64,node16-macos-x64,node16-win-x64 .
    - run: ls
    - run: echo ${{ env.RELEASE_VERSION }}
    - name: Rename binaries
      run: |
        mv cli-linux qyrus-cli-linux
        mv cli-macos qyrus-cli-macos
        mv cli-win.exe qyrus-cli-win.exe
    - name: Create github release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        name: ${{ env.RELEASE_VERSION }}
        files: |
          qyrus-cli-linux
          qyrus-cli-macos
          qyrus-cli-win.exe
