on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

name: Create Release tag

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.head_ref || github.ref_name }} 
          name: ${{ github.head_ref || github.ref_name }} 
          prerelease: false 
