on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

name: Create Release tag

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.head_ref || github.ref_name }} 
          release_name: ${{ github.head_ref || github.ref_name }} 
          draft: false 
          prerelease: false 
