name: create release branch

on:
  pull_request:
    branches:
      - 'master'
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create release branches
        run: |
          keywords="$(jq ".release_to_environments[]" .github/release_environment.json -r)"
          for keyword in $keywords; do
            echo "$keyword"
            git checkout -b release/$keyword
            git push --set-upstream origin release/$keyword
          done
