name: add-reviewers-infra-branch
on:
  pull_request:
    branches:
      - 'master'
    types: [opened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: '.github/infra_assign_configs.yml'
